/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package local.ages2;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author SCIS2-24
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnterAges = new javax.swing.JButton();
        btnConsultAges = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEnterAges.setText("Enter ages");
        btnEnterAges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterAgesActionPerformed(evt);
            }
        });

        btnConsultAges.setText("Consult ages");
        btnConsultAges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultAgesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(btnEnterAges)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultAges)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnterAges)
                    .addComponent(btnConsultAges))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultAgesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultAgesActionPerformed
        JOptionPane.showMessageDialog(rootPane, String.format(
                "Minors: %s\nSeniors: %s\nOlder adults: %s",
                Arrays.toString(minors),
                Arrays.toString(seniors),
                Arrays.toString(olderAdults)
        ));
    }//GEN-LAST:event_btnConsultAgesActionPerformed

    int[] minors = new int[5];
    int minorsPos = 0;

    int[] seniors = new int[5];
    int seniorsPos = 0;

    int[] olderAdults = new int[5];
    int olderAdultsPos = 0;

    private void btnEnterAgesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEnterAgesActionPerformed
        while (minorsPos + seniorsPos + olderAdultsPos < 15) {
            this.enterAges();
        }

        JOptionPane.showMessageDialog(rootPane, "There is enough data.");
    }

    private String showPromptAgeDialog() {
        return JOptionPane.showInputDialog(rootPane, String.format(
                "Count: %d minors, %d seniors and %d older adults.\n\nEnter an age:",
                minorsPos,
                seniorsPos,
                olderAdultsPos));
    }

    private int promptAge() {
        while (true) {
            String rawAge = showPromptAgeDialog();

            if (rawAge.chars().allMatch(Character::isDigit)) {
                return Integer.parseInt(rawAge);
            }

            JOptionPane.showMessageDialog(rootPane, "Only integers are accepted!");
        }
    }

    private void enterAges() {
        int age = promptAge();

        if (age < 18) {
            if (minorsPos >= 5) {
                JOptionPane.showMessageDialog(rootPane, "Already has 5 minors.");
                return;
            }

            this.minors[minorsPos] = age;
            this.minorsPos++;

            JOptionPane.showMessageDialog(rootPane, "The minor has been added.");

            return;
        }

        if (age < 60) {
            if (seniorsPos >= 5) {
                JOptionPane.showMessageDialog(rootPane, "Already has 5 seniors.");
                return;
            }

            this.seniors[seniorsPos] = age;
            this.seniorsPos++;

            JOptionPane.showMessageDialog(rootPane, "The senior has been added.");

            return;
        }

        if (olderAdultsPos >= 5) {
            JOptionPane.showMessageDialog(rootPane, "Already has 5 older adults.");
            return;
        }

        this.olderAdults[olderAdultsPos] = age;
        this.olderAdultsPos++;

        JOptionPane.showMessageDialog(rootPane, "The older adult has been added.");
    }// GEN-LAST:event_btnEnterAgesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultAges;
    private javax.swing.JButton btnEnterAges;
    // End of variables declaration//GEN-END:variables
}
